/**
 * `window.__DBT_DOCS__` — build-scoped facts inlined into `index.html`.
 *
 * `dbt docs generate` injects this at export time (see the Rust `export::bootstrap`
 * module). It carries facts about the *build* rather than about the data: the dbt
 * version that produced the site, which distribution produced it, whether
 * analytics is consented, and where to fetch DuckDB-WASM. Being inlined means it
 * costs no request and is readable before any parquet loads.
 *
 * Every deployment has it: `dbt docs generate` injects it, and the `devSite` Vite
 * plugin injects an equivalent in development. Its absence means the page was served
 * by something that did not generate it — a partial copy, a stale `index.html` beside
 * fresh assets — which `main.tsx` treats as fatal rather than degrading into an app
 * with no data layer.
 *
 * Deliberately absent: anything derivable from the artifact set. There is no
 * `has_column_lineage` here — that comes from whether `dbt.column_lineage.parquet`
 * loaded with rows, so there is one source of truth rather than two that can
 * disagree.
 */

/** Bumped by the exporter when this shape changes incompatibly. */
export const SUPPORTED_BOOTSTRAP_SCHEMA_VERSION = 1;

/** Fallback when the bootstrap omits `data_dir`. Matches the exporter's `DATA_DIR`. */
const DEFAULT_DATA_DIR = 'index/';

export interface SiteTelemetry {
  enabled: boolean;
  dbt_cloud_account_identifier: string;
  dbt_cloud_project_id: string;
  dbt_cloud_environment_id: string;
}

export interface SiteBootstrap {
  schema_version: number;
  generated_at: string;
  dbt_version: string;
  distribution: string;
  is_logged_in: boolean;
  duckdb_cdn_base: string;
  /** Directory holding the parquet, relative to `index.html`. Trailing slash. */
  data_dir: string;
  telemetry: SiteTelemetry;
}

declare global {
  interface Window {
    __DBT_DOCS__?: SiteBootstrap;
  }
}

/**
 * The injected bootstrap, or `null` if it is missing or unreadable.
 *
 * An unrecognized `schema_version` is treated as absent rather than read
 * optimistically: a stale `index.html` beside fresh assets may have moved fields, and
 * silently misreading telemetry consent is the failure mode that matters.
 */
export function readSiteBootstrap(): SiteBootstrap | null {
  const raw = typeof window === 'undefined' ? undefined : window.__DBT_DOCS__;
  if (!raw || typeof raw !== 'object') return null;
  if (raw.schema_version !== SUPPORTED_BOOTSTRAP_SCHEMA_VERSION) {
    // eslint-disable-next-line no-console
    console.warn(
      `dbt docs: ignoring bootstrap with unsupported schema_version ${raw.schema_version} ` +
        `(expected ${SUPPORTED_BOOTSTRAP_SCHEMA_VERSION}); regenerate the site with ` +
        `a matching dbt version`,
    );
    return null;
  }
  return raw;
}

/** Whether the page carries a readable bootstrap. Every generated site does; this
 *  distinguishes "generated by a dbt we understand" from a stale or partial copy. */
export function hasSiteBootstrap(): boolean {
  return readSiteBootstrap() !== null;
}

/**
 * Absolute base URL of the directory holding the parquet artifacts.
 *
 * The directory name comes from the bootstrap rather than being hardcoded: the site
 * is written to the dbt target directory so its `index.html` sits where core v1 put
 * it, and `<target>/data/` already belongs to stored test failures.
 *
 * Resolved against `document.baseURI` rather than `location.pathname` so the site
 * works unmodified from any subpath — a GitLab Pages project site lives under
 * `/<group>/<project>/`. Hash routing is what makes this sound: the document URL's
 * path never changes as the user navigates, so this stays correct after a deep
 * link.
 */
export function dataBaseUrl(): string {
  const dir = readSiteBootstrap()?.data_dir ?? DEFAULT_DATA_DIR;
  return new URL(dir, document.baseURI).href;
}
