import type { Meta, StoryObj } from '@storybook/react-vite';

import { ColumnCard } from './ColumnCard';

const meta: Meta<typeof ColumnCard> = {
  component: ColumnCard,
  args: {
    name: 'customer_id',
    type: 'varchar',
    description: 'Surrogate key for the customer. Unique and never reused.',
  },
  // The card is an `<li>`; without a list wrapper the markup is invalid and the
  // spacing is not what the page shows.
  decorators: [(Story) => <ul className="max-w-xl space-y-2">{Story()}</ul>],
};

export default meta;
type Story = StoryObj<typeof ColumnCard>;

export const Default: Story = {};

/** The description paragraph is dropped entirely rather than left blank, so the card
 *  shrinks to a single row. */
export const WithoutDescription: Story = {
  args: { description: null },
};

/** No type still renders the badge — empty. Worth pinning: it is a small visual bug
 *  a type-less export makes common. */
export const WithoutType: Story = {
  args: { type: null },
};

export const LongDescription: Story = {
  args: {
    description:
      'Surrogate key for the customer, generated by hashing the source system id ' +
      'together with the loader tenant so that ids from two source systems cannot ' +
      'collide. Stable across full refreshes.',
  },
};
