[package]
# TODO: Rename this crate to dbt-vortex-events. End state:
# - vortex-client (generic)
# - dbt-vortex (the client state for dbt)
# - dbt-vortex-events (the events logged by dbt)
# Other binaries log a different set of events through the vortex-client.
name = "vortex-events"
version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
edition.workspace = true

[dependencies]
proto-rust = { path = "../proto-rust" }

dbt-common = { workspace = true }
dbt-env = { workspace = true }
dbt-fusion-workspace-hack = { version = "0.1" }
dbt-jinja-utils = { workspace = true }
dbt-schemas = { workspace = true }
dbt-vortex = { workspace = true }
dbt-yaml = { workspace = true }

base64 = { workspace = true }
dirs = { workspace = true }
md5 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
vortex-client = { workspace = true }


[lib]
name = "vortex_events"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
